# Generated by Django 4.2.7 on 2023-12-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='recipient',
            field=models.CharField(blank=True, default='self', max_length=255),
        ),
    ]
