# Generated by Django 4.2.7 on 2023-12-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='recipient',
            field=models.CharField(default='self', max_length=255),
        ),
    ]
