# Generated by Django 4.2.7 on 2023-12-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='recipient',
        ),
        migrations.AddField(
            model_name='expense',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
