# Generated by Django 4.2.7 on 2023-12-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_remove_expense_recipient_expense_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
