# Generated by Django 5.0 on 2023-12-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepad', '0003_alter_note_description_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, default='description can be empty'),
            preserve_default=False,
        ),
    ]
